version: "3.8"
services:
  service1:
    image: 378834093760.dkr.ecr.us-east-1.amazonaws.com/service1:latest
    ports:
      - "5000:5000"
    restart: always
  service2:
    image: 378834093760.dkr.ecr.us-east-1.amazonaws.com/service2:latest
    ports:
      - "5001:5001"
    restart: always
